# 配置服务端口号
server:
  port: 10100

# 配置数据库的连接信息
spring:
  # 每一个服务注册到nacos注册中心都需要提供一个服务名称
  application:
    name: spzx-cloud-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-user?characterEncoding=UTF8
    username: root
    password: root
    # 配置nacos注册中心的地址
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
    map-underscore-to-camel-case: true #以驼峰命名的方式映射字段
  type-aliases-package: com.atguigu.spzx.cloud.entity #实体类别名
  mapper-locations: classpath:/mapper/*.xml #xml映射文件